### ISSUE TITLE
Shearing Problems

### ISSUE THREAD

**Issue by cojored** [TapL-Recreation-Project/OPShearing#1]
[00:13:46 ERROR]: Could not pass event PlayerShearEntityEvent to OPShearing v1.0-SNAPSHOT
java.lang.IndexOutOfBoundsException: Index: 52, Size: 50

That happens when I shear only sometimes though

MC 1.16.5

**Comment by notnotnotswipez** [comment]
Your config has mismatched data it seems

**Comment by notnotnotswipez** [comment]
Can you send your config? There should be an equal amount of numbers and item entries

**Comment by cojored** [comment]
> Your config has mismatched data it seems

Oh ok thats my fault oops
